chore: fix console-subscriber on tokio 1.21.0
tokio-rs/console pull request #374
Opened 2022-09-03 22:05 UTC by Noah-Kennedy

Due to a change in the unstable task builder APIs, this no longer compiles with the latest version of Tokio.

Fortunately, it's a simple fix.

2022-09-03 22:48 UTC, Noah-Kennedy commented
Ah, crap, need to fix CI.

2022-09-04 00:39 UTC, hawkw requested changes
Thanks for the fix!

It looks like CI is still broken because the examples also use `task::Builder`: https://github.com/tokio-rs/console/pull/374#issuecomment-1236209338

Mind fixing them as well?

2022-09-04 05:35 UTC, Noah-Kennedy commented
I'll get these fixed tomorrow morning.

2022-09-04 18:02 UTC, Noah-Kennedy commented
Hmm, CI seems to be failing for things unrelated to this PR.

2022-09-04 18:02 UTC, Noah-Kennedy commented
Looks like Clippy lints.

2022-09-04 18:03 UTC, Noah-Kennedy commented
@hawkw should I fix those in another PR or in this one?

2022-09-04 20:09 UTC, hawkw commented
> @hawkw should I fix those in another PR or in this one?

i'd prefer them to be fixed separately, but it's not a huge deal.

2022-09-04 20:10 UTC, Noah-Kennedy commented
That would be my preference as well, but I wanted to check with you first. I'll put up the PR shortly.

2022-09-04 20:32 UTC, Noah-Kennedy commented
@hawkw I've posted #375, which should fix this.

2022-09-04 20:58 UTC, hawkw approved these changes

2022-09-04 21:00 UTC, Noah-Kennedy commented
Thanks for the review!

2022-09-04 21:02 UTC, merged