feat(console): Add way to inspect details of task from resource view
tokio-rs/console pull request #449
Opened 2023-07-11 10:34 UTC by guerinoni

Now it is possible while navigate in `async_ops_table` to go directly to
details of the task that you are pointing on the list.

This closes #448

2023-07-13 15:46 UTC, hds requested changes
Thank you for fixing that error!

I've got a few code suggestions to avoid `unwrap()` and make some parts clearer on first read through.

2023-07-13 15:46 UTC, hds commented on tokio-console/src/view/mod.rs
> +                                    });
The `Id<Task>` can be compared directly, so it doesn't need to be turned into a string and then parsed to a u64.

Also, let's call the result `task`, as I think it's clearer than `item`.

```suggestion
                                let task = self
                                    .tasks_list
                                    .sorted_items
                                    .iter()
                                    .filter_map(|i| i.upgrade())
                                    .find(|t| task_id == t.borrow().id());
```

2023-07-13 15:46 UTC, hds commented on tokio-console/src/view/mod.rs
> +                                }
We've got a preference for longer variable names to make things clearer without an IDE. Also, we can shadow the variable name so we don't need to pick something different.
```suggestion
                                if let Some(task) = task {
                                    update_kind = UpdateKind::SelectTask(task.borrow().span_id());
                                    self.state = TaskInstance(self::task::TaskView::new(
                                        task,
                                        state.task_details_ref(),
                                    ));
                                }
```

2023-07-13 15:46 UTC, hds commented on tokio-console/src/view/resource.rs
> +    pub async_ops_table: TableListState<AsyncOpsTable, 9>,
Let's make this `pub(crate)` to match the struct it's in.

```suggestion
    pub(crate) async_ops_table: TableListState<AsyncOpsTable, 9>,
```

2023-07-13 20:10 UTC, hds approved these changes
Looks good to me. Thank you!

2023-07-14 18:26 UTC, hds commented
@hawkw when you've got a moment, would you like to have a look at this PR.

2023-07-14 23:11 UTC, hawkw approved these changes
this looks good to me! i wonder if we ought to add "enter: select task" to the help text as well?

2023-07-15 12:44 UTC, guerinoni commented
> this looks good to me! i wonder if we ought to add "enter: select task" to the help text as well?

Hey, it is already there
<img width="735" alt="Screenshot 2023-07-15 at 2 43 42 PM" src="https://github.com/tokio-rs/console/assets/41150432/b017f45d-1220-4c07-a366-0961530e82a5">

It is `view details`, in this context means task's details.

2023-07-24 17:07 UTC, hds commented
> this looks good to me! i wonder if we ought to add "enter: select task" to the help text as well?

@hawkw We could probably improve the text on the controls list, but I would do that in a separate change since the enter key was already listed (erroneously) on this view and so it's somewhat unrelated.

2023-07-28 21:39 UTC, merged