fix(console): fix task detail view Id, now using remote tokio::task::Id
tokio-rs/console pull request #455
Opened 2023-08-03 09:03 UTC by inevity

Now home page task list show id using remote tokio::task::Id, but task detail view show Id using local sequential id in the console client, so both id is not same.
The pr fix the console/client to show id using remote tokio::task::Id.

2023-08-17 08:57 UTC, hds requested changes
Thank you for finding and fixing this error! Your PR can be simplified a little bit using the same method as in the list view.

The tokio task ID is already stored on the `state::Task` struct as `id_str` (and already parsed to a string for quick rendering) and exposed by a method of the same name.

You can use that direclty instead of the new `task_id()` method.

If you would like to do so, it would make sense to rename the existing field and method to `task_id_str`. But this is optional.

2023-08-17 08:57 UTC, hds commented on tokio-console/src/view/task.rs
> +            Span::raw(format!("{} ", task.task_id())),
We already have a method which returns a `&str` of the tokio task ID (and so doesn't require `unwrap_or`).

```suggestion
            Span::raw(format!("{} ", task.id_str())),
```

2023-08-18 14:12 UTC, inevity commented on tokio-console/src/view/task.rs
> +            Span::raw(format!("{} ", task.task_id())),
Chang to use id_str().
As for rename the existing field from id_str to task_id_str. Found AsyncOpStats have a member named task_id_str,and AsyncOp have method task_id_str. Resource has a member id_str, and member id_str. So look like the name convention is not consistency.  So should open another pr to rename all names, such as should not use id, use seq_id or another name to name the console seq id, so that we can see the difference for the names  of seqid, taskid, spanid, resid etc

2023-08-18 14:46 UTC, hds approved these changes
Great, thank you for your PR!

2023-08-18 14:52 UTC, merged