Bump the h2 from 0.3 to 0.4
tokio-rs/console pull request #499
Opened 2023-12-07 13:49 UTC by hi-rustin

The main change: `update to `http` 1.0.`

2024-01-09 14:43 UTC, hds requested changes
Thanks for your PR. Would you mind commenting on the fact that we'll now have 2 versions of the `http` crate in our dependency tree (because `tonic` hasn't updated to the latest `axum` yet, and `axum` 0.6 is still depending on `http` 0.2).

I'm not against merging this, I just want to make sure that we're aware of what we're doing.

2024-01-09 14:43 UTC, hds commented on Cargo.lock
> + "http 0.2.9",
We'll now have 2 versions of the `http` crate in our dependencies. I'm not against, this, but I'd like to double check that you're aware of this before merging.

2024-01-09 14:45 UTC, seanmonstar commented
I think the `h2` dependency is used in the Console to access stuff inside Tonic. In that case, they should be kept in sync.

2024-01-09 15:03 UTC, hds commented
> I think the `h2` dependency is used in the Console to access stuff inside Tonic. In that case, they should be kept in sync.

Yep, @seanmonstar is right, upgrading the version of `h2` would break this check:

https://github.com/tokio-rs/console/blob/ef61081caa6c20f9495563855969e8d820559dfe/tokio-console/src/conn.rs#L43-L47

Good catch!

@hi-rustin Let's close this PR.

2024-01-09 15:16 UTC, seanmonstar commented
As a side note, I'd recommend trying to figure out a way to do that without downcasting the error. Either in Console, or in Tonic. It is not part of [hyper's stability promise](https://docs.rs/hyper/latest/hyper/struct.Error.html#source).

2024-01-09 16:11 UTC, hi-rustin commented
> upgrading the version of `h2` would break this check:

How about I add some comments about it? I think it would be useful to be aware of it.

2024-01-09 16:16 UTC, seanmonstar commented
A comment in the Cargo.toml file could be helpful, right next to the dependency declaration.

2024-01-09 17:22 UTC, hds commented
Yes, that's a good idea. It would be nice if we could add some sort of a unit test for the behaviour in `conn.rs` as well.

2024-01-17 14:19 UTC, hds approved these changes
Great, thanks for clarifying this!

2024-01-22 10:05 UTC, merged

2024-01-22 10:33 UTC, hi-rustin commented
Thanks for your review!  💚 💙 💜 💛 ❤️