Update README.md
tokio-rs/console pull request #510
Opened 2024-01-20 16:26 UTC by SimonsMine

Added note about windows

2024-01-21 10:10 UTC, hi-rustin requested changes
<img width="452" alt="image" src="https://github.com/tokio-rs/console/assets/29879298/eb22222d-2b12-45cf-9cd3-c24dbc6f3f95">


It seemed you lost a `)` here.

2024-01-21 21:10 UTC, SimonsMine commented on README.md
> +For best results on windows use a utf-8 enabled Terminal such as the new Windows [Terminal]([http://example.com](https://learn.microsoft.com/en-us/windows/terminal/install).
```suggestion
For best results on windows use a utf-8 enabled Terminal such as the new Windows [Terminal](https://learn.microsoft.com/en-us/windows/terminal/install).
```

2024-01-21 21:10 UTC, SimonsMine commented
fixed : )

2024-01-22 17:46 UTC, hawkw requested changes
Thanks for helping to improve the documentation!

I suggested some edits to the note on UTF-8 support, let me know what you think?

Also, would you mind adding a similar note to the `tokio-console` crate's README, in [the "running the console" section](https://github.com/tokio-rs/console/blob/main/tokio-console/README.md#using-the-console)? That documentation is rendered on https://crates.io/crates/tokio-console and https://docs.rs/tokio-console, so it would be nice to include the Windows support information there as well.

2024-01-22 17:46 UTC, hawkw commented on README.md
> +In order to get graph output and other visual features to work, make sure to explicitly call tokio-console with the utf-8 language flag set.
I might rephrase this a bit:
```suggestion
The console uses the UTF-8 character set to display graphs and other visual
features in the terminal. In order to display this rich terminal UI on Windows,
it's necessary to use a UTF-8-enabled terminal emulator, such as the new
[Windows Terminal](https://learn.microsoft.com/en-us/windows/terminal/install).

If you're using a terminal that supports UTF-8, make sure to explicitly call
tokio-console with the UTF-8 language flag set: 
```

2024-02-05 09:13 UTC, SimonsMine commented
Applied suggestions : )

2024-02-06 17:26 UTC, hawkw approved these changes

2024-05-23 14:05 UTC, hi-rustin approved these changes
Looks good to me. Thanks! 👍

2024-05-23 14:17 UTC, merged