feat: Adjust task and waker panel for long names
tokio-rs/console pull request #527
Opened 2024-02-17 18:18 UTC by devanbenz

- Makes better use of waker and task panel spacing
- Puts Last woken on its own line
- wraps text within the task panel for really long location names

Updated:
![task_long_name](https://github.com/tokio-rs/console/assets/22461703/4959126b-4796-4286-b097-45978948b62d)
![task_no_name](https://github.com/tokio-rs/console/assets/22461703/66f79bd0-4384-4151-9cdd-3aeec4f8fcd4)

2024-02-18 21:56 UTC, hds requested changes
I haven't had a chance to look to much into the code yet. But from the screenshots, it looks like you're losing lines from the Task panel (I see the scheduled and idle times missing from the bottom).

I'm not sure if you've noticed this, but the task panel will need to have a variable height, whereas right now the height is fixed.

Also, I think that we probably don't need to put the location on its own line (after the label), it should be able to start on the line with the label and then break onto additional lines if it needs to.

I'll come back with a complete review (hopefully tomorrow) once I've had a chance to read the code changes.

2024-02-18 22:15 UTC, devanbenz commented
Ah! Yes, good call. I did not notice that. I’ll need to make some
adjustments

On Sun, Feb 18, 2024 at 3:56 PM Hayden Stainsby ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> I haven't had a chance to look to much into the code yet. But from the
> screenshots, it looks like you're losing lines from the Task panel (I see
> the scheduled and idle times missing from the bottom).
>
> I'm not sure if you've noticed this, but the task panel will need to have
> a variable height, whereas right now the height is fixed.
>
> Also, I think that we probably don't need to put the location on its own
> line (after the label), it should be able to start on the line with the
> label and then break onto additional lines if it needs to.
>
> I'll come back with a complete review (hopefully tomorrow) once I've had a
> chance to read the code changes.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tokio-rs/console/pull/527#pullrequestreview-1887337745>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFLL2BYL3QMKR5TYSLC3OQTYUJ2HXAVCNFSM6AAAAABDNPUN36VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQOBXGMZTONZUGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-02-19 18:17 UTC, hds reviewed
A few more comments based on reading the changes this time.

2024-02-19 18:17 UTC, hds commented on tokio-console/src/view/task.rs
> +use ratatui::widgets::Wrap;
style: merge this with the other ratatui imports ok the next line.

2024-02-19 18:17 UTC, hds commented on tokio-console/src/view/task.rs
> +                    layout::Constraint::Percentage(60),
I think we might want something more dynamic than this. What do you think?

2024-02-28 00:18 UTC, devanbenz commented
Will be coming back to this PR this weekend! Sorry I was out of town last week/over the weekend :D

2024-05-16 13:01 UTC, 0xPoe commented
@devanbenz Friendly ping~ Do you have time to work on it again? Thanks!

2024-05-19 04:16 UTC, devanbenz commented
> @devanbenz Friendly ping~ Do you have time to work on it again? Thanks!

I definitely want to get back to this. I have an interview this week and a talk during the weekend. I have a feeling that afterwards I will likely be able to start contributing to open source more 👍

2025-04-14 05:32 UTC, hds commented
This PR has been superceded by #614, so I'll close it out.

2025-04-14 05:32 UTC, closed without merging