refactor: match span id earlier
tokio-rs/console pull request #535
Opened 2024-03-28 13:50 UTC by hi-rustin

Simplify code. same as https://github.com/tokio-rs/console/pull/533

2024-03-28 14:31 UTC, hi-rustin reviewed
🔢 Self-check (PR reviewed by myself and ready for feedback.)

2024-03-28 14:31 UTC, hi-rustin commented on tokio-console/src/view/mod.rs
> +    #[allow(dead_code)]
We might use this in the future. So I just allow the dead code check. Please let me know if we want to remove it.

2024-04-01 13:50 UTC, hds requested changes
This looks good.

Would you mind splitting the change to make clippy happy into another PR though? It's best to not mix concerns.

2024-04-01 13:50 UTC, hds commented on tokio-console/src/view/mod.rs
> +    #[allow(dead_code)]
I'm not sure why this isn't used but `SelectTask(u64)` is.

2024-04-01 14:29 UTC, hi-rustin commented on tokio-console/src/view/mod.rs
> +    #[allow(dead_code)]
I think we used the task ID to monitor task details, but we don't need to use it for resources.

2024-04-01 14:33 UTC, hi-rustin commented
> Would you mind splitting the change to make clippy happy into another PR though? It's best to not mix concerns.

Dropped. I will open a new PR for it.

2024-04-01 14:41 UTC, hi-rustin commented
> > Would you mind splitting the change to make clippy happy into another PR though? It's best to not mix concerns.
> 
> Dropped. I will open a new PR for it.

See: https://github.com/tokio-rs/console/pull/536

2024-04-01 19:39 UTC, hds approved these changes
This looks good. Thank you very much!

Could you please make sure that the commit message follows our styling for the `console` repo. This is the basis for our release notes, so it's important. We follow [conventional commits], but checking the summary in the **Commit message guidelines** section of the [CONTRIBUTING.md] document is probably enough.

In this case, the commit message should be something like (both `refac` and `refactor` are accepted, see https://github.com/tokio-rs/console/blob/main/cliff.toml#L80):

```
refac(console): match span id earlier (#535)

Follow the same pattern applied in #533 to match the span id
earlier to avoid checking twice.
```

[conventional commits]: https://www.conventionalcommits.org/en/v1.0.0/
[CONTRIBUTING.md]: https://github.com/tokio-rs/console/blob/main/CONTRIBUTING.md#commit-message-guidelines

2024-04-06 14:48 UTC, hi-rustin commented
@hds Updated. Thanks! I didn't know that we also needed to include a detailed commit body. I thought that the Pull Request body was enough, although my PR body wasn't very good either. I'll make sure to add it next time.

2024-04-06 14:50 UTC, merged