feat(console): add large future lint
tokio-rs/console pull request #587
Opened 2024-10-01 10:42 UTC by hds

In Tokio, the futures for tasks are stored on the stack unless they are
explicitly boxed. Having very large futures can be problematic as it can
cause a stack overflow.

This change makes use of new instrumentation in Tokio
(tokio-rs/tokio#6881) which includes the size of the future which drives
a task. The size isn't given its own column (we're running out of
horizontal space) and appears in the additional fields column.

A new lint has been added for large futures. By default it will show a
warning when a task's future is greater than or equal to 2048 bytes.
This value was chosen as it is the threshold at which Tokio will box a
future in debug mode. The lint has been added to the list of default
lints.

2024-10-01 10:42 UTC, hds commented
I'll keep this in draft until the Tokio PR is merged, as this feature is useless without it.

2024-10-08 12:02 UTC, hds commented
The dependent change in Tokio tokio-rs/tokio#6881 has been merged, so this is good to go.

2024-10-08 16:17 UTC, hawkw requested changes
This is really cool --- I love seeing new lints I hadn't thought of being added to the console!

I had some very small suggestions about the wording of the lint text, and noticed some stuff was missing from the docs. Other than that, the implementation looks great!

2024-10-08 16:17 UTC, hawkw commented on tokio-console/src/warnings.rs
> +            description: format!("tasks are large (threshold {} bytes)", min_size),
nitpicky: what about 
```suggestion
            description: format!("tasks are {} bytes or larger", min_size),
```

2024-10-08 16:17 UTC, hawkw commented on tokio-console/src/warnings.rs
> +            "This task was auto-boxed by the runtime due to its size (originally \
what do you think about adding a little more detail here:
```suggestion
            "This task's future was auto-boxed by the runtime when spawning, due to its size (originally \
```

2024-10-08 16:17 UTC, hawkw commented on tokio-console/src/config.rs
> +    ///                     stack space.
It looks like the `auto-boxed-future` warning is missing from the docs here?

2024-10-08 16:17 UTC, hawkw commented on tokio-console/src/config.rs
> +    ///
Again, `auto-boxed-future` is missing.

2024-10-08 16:17 UTC, hawkw commented on tokio-console/src/config.rs
> +    /// [possible values: all, self-wakes, lost-waker, never-yielded, large-future]
```suggestion
    /// [possible values: all, self-wakes, lost-waker, never-yielded, large-future, auto-boxed-future]
```

2024-10-08 17:38 UTC, hds commented on tokio-console/src/config.rs
> +    ///
Fixed.

2024-10-08 17:38 UTC, hds commented on tokio-console/src/config.rs
> +    ///                     stack space.
Fixed.

2024-10-08 18:41 UTC, hawkw reviewed
Oh, one last thing: since this change depends on new Tokio instrumentation, can we add something stating which version of Tokio these lints will be available in to the list of Tokio versions here: https://github.com/tokio-rs/console/tree/main/console-subscriber#required-tokio-versions

Also, I assume you've tested that the console still works fine with prior tokio versions that are missing the task-size fields? It seems like it ought to, but it's probably worth making sure...

2024-10-08 20:45 UTC, hds commented
@hawkw Good point about the Tokio version! I had tested an earlier version against the current version of Tokio, but it was good that I tested it again, after modifying the large blocking task I had accidentally made it so large that in the Tokio 1.40.0 (and lower) it was causing a stack overflow (just in the example application, but all the same) because that blocking task wasn't being auto-boxed.

Fixed that now and confirmed that everything works fine in the current version of Tokio, just that there is no size information and so the lints won't ever trigger.

2024-10-08 21:50 UTC, hawkw approved these changes
looks good to me whenever CI is satisfied!

2024-10-09 12:18 UTC, merged